---
- name: Include system dependant vars
  include_vars:
    file: "{{ ansible_system }}_{{ ansible_architecture }}.yml"

- name: Download kapow
  get_url:
    url: "{{ kapow_dist_base_url }}/v{{ kapow_version }}/kapow_{{ kapow_version }}_{{ kapow_arch }}"
    dest: "{{ kapow_bin_dir }}/kapow"
    mode: '0755'
    checksum: "{{ kapow_checksum }}"

- name: Create kapow service account
  user:
    name: "{{ kapow_user }}"
    comment: kapow service account
    state: present
    system: yes
    
- name: Configure kapow systemd service
  template:
    src: kapow.service.j2
    dest: "/etc/systemd/system/{{ kapow_service }}.service"

- name: Enable kapow systemd service
  systemd:
    name: "{{ kapow_service }}"
    state: started
    enabled: yes
    daemon_reload: yes
